# MPV no longer replaces on screen controls with the default one (good for custom themes)
osc=no
border=yes

# GPU & audio settings for a better viewing experience (tailored for high-end PCs)
profile=high-quality
vo=gpu-next
hwdec=auto
audio-channels=stereo,5.1,7.1
cache=yes
gpu-api=auto

# Misc settings
save-position-on-quit=no
cursor-autohide=1500

# Default volume always starts at 100% and maxes out at 100%
volume=100
volume-max=100

# Converts HDR content to SDR (remove this if you are using HDR)
tone-mapping=bt.2390
tone-mapping=bt.2446a
tone-mapping=st2094-40
